name: Build
on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          uv sync --group build --locked

      - name: Install ruff
        run: |
          uv tool install ruff

      - name: Lint
        run: |
          uv tool run ruff check --output-format=github

      - name: Check format
        run: |
          uv tool run ruff format --diff

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Timestamp
        id: timestamp
        shell: pwsh
        run: |
          $timestamp = git show -s --format="format:%ct"
          "timestamp=$timestamp" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          architecture: "x86"

      - name: Install dependencies
        run: |
          uv sync --group build --locked

      - name: Build
        run: |
          uv run .\build.bat
        env:
          PYTHONHASHSEED: 0
          SOURCE_DATE_EPOCH: ${{ steps.timestamp.outputs.timestamp }}

      - name: Checksum
        run: |
          Get-FileHash dist\addglyph.exe -Algorithm SHA256 | Format-List

      - name: Pack
        run: |
          cp usage.txt dist
          cp license_dist.txt dist\license.txt
          Compress-Archive -Path dist\* -DestinationPath dist.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact
          path: dist.zip

  release:
    needs: windows-build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get tag name
        id: tag
        run: |
          tag_name=${GITHUB_REF##*/}
          echo "zip_file_name=addglyph_${tag_name}.zip" >> "${GITHUB_OUTPUT}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build-artifact

      - name: Rename
        run: |
          mv "dist.zip" "${zip_file_name}"
        env:
          zip_file_name: ${{ steps.tag.outputs.zip_file_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.tag.outputs.zip_file_name }}
          draft: true
