name: Build
on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x86"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==5.3

      - name: Build
        run: |
          .\build.bat

      - name: Pack
        run: |
          cp usage.txt dist
          cp license_dist.txt dist\license.txt
          Compress-Archive -Path dist\* -DestinationPath dist.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact
          path: dist.zip

  release:
    needs: windows-build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get tag name
        id: tag
        run: |
          tag_name=${GITHUB_REF##*/}
          echo "zip_file_name=addglyph_${tag_name}.zip" >> "${GITHUB_OUTPUT}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build-artifact

      - name: Rename
        run: |
          mv "dist.zip" "${zip_file_name}"
        env:
          zip_file_name: ${{ steps.tag.outputs.zip_file_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.tag.outputs.zip_file_name }}
          draft: true
